<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/discuss.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">


        <!--主体内容-->
        <div class="nk-content">
            <div class="module-box">
                <div class="module-head clearfix">
                    <h2>志愿新闻</h2>
                </div>
                <div class="tags-box tag-mod">

                </div>
                <div class="menu-txt-box">
                    <ul class="menu-txt clearfix">
                        <li class="tag-label selected">最新发布</li>
                    </ul>
                </div>
                <div class="module-body">
                    <ul class="common-list">

                    <?foreach ($datas as $k => $v){?>
                        <li class="clearfix"> <a class="head-pic" data-card-uid="826546" href="#" data-card-index="1"></a>
                            <div class="discuss-detail">
                                <div class="discuss-main clearfix">
                                    <h3> <a href="/news/detail/id/<?=$v['id']?>" target="_blank"><?=$v['caption']?></a></h3>

                                </div>
                                <div class="feed-foot">
                                    <div class="feed-legend">
                                        <span><?=mb_substr($v['created_at'],6,1).'月'.mb_substr($v['created_at'],8,2).'日'.mb_substr($v['created_at'],10,9)?></span>
<!--                                        <span class="feed-legend-pipe">|</span>-->
<!--                                        <span>浏览<span class="feed-legend-num">6829</span></span>-->
                                    </div>
                                </div>
                            </div>
                        </li>

                        <?}?>

                    </ul>
                </div>
                <?= $page->show() ?>
            </div>
        </div>
        <!--主体内容结束-->

        <div class="nk-bar">

            <div class="module-box column-nk">
                <div class="module-head clearfix">
                    <h1>愿吧口号</h1>
                </div>
                <div class="module-body">
                    <span class="column-nk-time">青春北化，志愿你我</span>
                    <ul class="column-nk-list">
                        <li><div class="column-nk-txt">
                            </div>
                        </li>
                    </ul>
                </div>

            </div>

        </div>

    </div>
    <!--主体内容结束-->
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>