<script type="text/javascript" src="/assets/model_editor/volunteer_editor/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/assets/model_editor/volunteer_editor/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/assets/model_editor/volunteer_editor/ueditor/lang/zh-cn/zh-cn.js"></script>

<style>
    .top-news a {padding: 0px;TEXT-DECORATION:none}
</style>
<div class="col-md-12 news-page blog-page">
    <form method="post" action="/admin/volunteer/edit" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-9 blog-tag-data">
                <div class="post-comment">

                    <div class="form-group">
                        <label class="control-label">姓名</label>
                        <input type="text" name="username" value="" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input type="text" name="password" value="" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">学号</label>
                        <input type="text" name="student_id" value="" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">班级</label>
                        <input type="text" name="class" value="" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">学院</label>
                        <select name="academy_id">
                            <option value="1">化学工程学院</option>
                            <option value="2">材料科学与工程学院</option>
                            <option value="3">机电工程学院</option>
                            <option value="4">信息科学与技术学院</option>
                            <option value="5">经济管理学院</option>
                            <option value="6">理学院</option>
                            <option value="7">文法学院</option>
                            <option value="8">生命科学与技术学院</option>
                            <option value="9">国际教育学院</option>
                            <option value="10">能源学院</option>
                            <option value="11">巴黎居里工程师学院</option>
                            <option value="12">侯德榜工程师学院</option>
                            <option value="13">职业技术学院</option>
                            <option value="14">继续教育学院</option>
                        </select>
                    </div>

                    <button class="btn blue margin-top-10" type="submit">提交</button>
                </div>
            </div>

        </div>
    </form>
</div>
