<script type="text/javascript" src="/assets/model_editor/volunteer_editor/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/assets/model_editor/volunteer_editor/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/assets/model_editor/volunteer_editor/ueditor/lang/zh-cn/zh-cn.js"></script>

<style>
    .top-news a {padding: 0px;TEXT-DECORATION:none}
</style>
<div class="col-md-12 news-page blog-page">
    <form method="post" action="" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-9 blog-tag-data">
                <div class="post-comment">

                    <div class="form-group">
                        <label class="control-label">姓名</label>
                        <input type="text" name="username" value="<?=$datas['username']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input type="text" name="password" value="<?=$datas['password']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">学号</label>
                        <input type="text" name="student_id" value="<?=$datas['student_id']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">班级</label>
                        <input type="text" name="class" value="<?=$datas['class']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">学院</label>
                        <select onchange="volunteersave({id:<?=$datas['id']?>, academy_id:this.value})">
                            <? foreach (VolunteerModel::$academy as $k2 => $v2) { ?>
                                <option<? if ($datas['academy_id'] == $k2) echo ' selected' ?> value="<?=$k2?>"><?=$v2?></option>
                            <? } ?>
                        </select>

                    </div>

                    <button class="btn blue margin-top-10" type="submit">提交</button>
                </div>
            </div>

        </div>
    </form>
</div>

<script>
    function volunteersave(data) {
        $.post('/admin/volunteer/save', data, function (d) {
            alert(d.msg);
        }, 'json');
    }

</script>