<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>总队简介</title>
    <meta name="keywords" content="hello" />
    <meta name="description" content="hello" />
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/common.css" />
    <link rel="stylesheet" href="/css/detail.css" />

    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<!--中间幻灯片轮播-->
<div class="row">
    <div class="col-md-12 column">
        <div class="carousel slide" id="carousel-232573">
            <ol class="carousel-indicators">
                <li data-slide-to="0" data-target="#carousel-232573" class="active">
                </li>
                <li data-slide-to="1" data-target="#carousel-232573">
                </li>
                <li data-slide-to="2" data-target="#carousel-232573">
                </li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img alt="" src="/img/slide3.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            这次志愿者服务的经历也对我的人生产生了重大的影响。作为在学校里的学生、作为在社会里的个人，我们也应该学会服从、付出、充满热情。在接下来的日子里，我会继续努力，以党员的要求来要求自己，不断地完善自己，积极为人民服务。
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="/img/slide2.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            这次志愿者服务的经历也对我的人生产生了重大的影响。作为在学校里的学生、作为在社会里的个人，我们也应该学会服从、付出、充满热情。在接下来的日子里，我会继续努力，以党员的要求来要求自己，不断地完善自己，积极为人民服务。
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="/img/slide3.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            这次志愿者服务的经历也对我的人生产生了重大的影响。作为在学校里的学生、作为在社会里的个人，我们也应该学会服从、付出、充满热情。在接下来的日子里，我会继续努力，以党员的要求来要求自己，不断地完善自己，积极为人民服务。
                        </p>
                    </div>
                </div>

            </div> <a class="left carousel-control" href="#carousel-232573" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-232573" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
</div>
<!--中间幻灯片轮播-->


<div id="wrapper" style="padding:5%;">
    <div id="pager">

        <? foreach ($values as $value)?>

        <!--top -->
        <div class="zyd-main w-1000 cf">
            <!--tab -->
            <div class="zyd-tab mar-t20 mar-r20 f_l">
                <div id="fixed" style="position: relative; top: 0px;" class="">
                    <ul class="tabnav cf">
                        <li class="active">总队介绍</li>
                    </ul>
                </div>

                <!--tabcon -->
                <div class="tabcon" style="padding-top: 0px;">
                    <div class="ke-detail active">
                        <br/>

                        <p><?=$value['content']?>
                        </p>

                    </div>

                </div>
                <!--tabcon -->
            </div>
            <!--tab -->

            <!---aside -->
            <div class="zyd-aside mar-t20 f_r">
                <h3 class="caption">全称</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['full_name']?></span>
                        </div>
                    </li>
                </ul>

                <h3 class="caption">口号</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['slogan']?></span>
                        </div>
                    </li>
                </ul>
                <h3 class="caption">组成</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['compose']?></span>
                        </div>
                    </li>
                </ul>
                <h3 class="caption">宗旨</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['aim']?></span>
                        </div>
                    </li>
                </ul>
                <h3 class="caption">建设方针</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['constr_policy']?></span>
                        </div>
                    </li>
                </ul>

            </div>
            <!--aside -->
        </div>

    </div>
</div>

<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>