<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>一起志愿吧</title>
    <meta name="keywords" content="一起志愿吧"><!--关键词-->
    <meta name="description" content="北京化工大学志愿服务总队"><!--描述-->

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!-- 引入css -->
    <link rel="stylesheet" type="text/css" href="/css/jquery.fullPage.css" />
    <link rel="stylesheet" type="text/css" href="/css/full_page.css" />
    <!-- fullpage.js依赖于jquery库 -->
    <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery.fullPage.min.js"></script>

    <script type="text/javascript">
        $(function() {
            $("#ido").fullpage();
        });
    </script>

</head>
<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<div id="ido">
    <div class="section section1 section1Img  text-center active">
        <h3>每一个section是一屏，这是第二屏</h3>
<!--        <img alt="" src="/img/volunteer_intro.jpg" />-->

    </div>
    <div class="section section2 section2Img text-center " >
        <h3>每一个section是一屏，这是第二屏</h3>
    </div>
    <div class="section section3 text-center">
        <h3>每一个section是一屏，这是第三屏</h3>
    </div>
    <div class="section section4 text-center">
        <h3>每一个section是一屏，这是第四屏</h3>
    </div>
</div>

</body>
</html>