<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>总队简介</title>
    <meta name="keywords" content="hello" />
    <meta name="description" content="hello" />
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/common.css" />
    <link rel="stylesheet" href="/css/detail.css" />

    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<!--中间幻灯片轮播-->
<div class="row">
    <div class="col-md-12 column">
        <div class="carousel slide" id="carousel-232573">
            <ol class="carousel-indicators">
                <li data-slide-to="0" data-target="#carousel-232573" class="active">
                </li>
                <li data-slide-to="1" data-target="#carousel-232573">
                </li>
                <li data-slide-to="2" data-target="#carousel-232573">
                </li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img alt="" src="/img/slide1.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            北京化工大学志愿服务总队引导青年志愿者竭诚为广大同学服务，以“立足学校，服务社会，提高全校志愿者的综合素质，创造校园文化的和谐氛围，树立化工大学的良好形象，为构建和谐社会不懈努力”为奋斗目标，用实际行动诠释着“奉献、友爱、互助、进步”的志愿服务精神。
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="/img/slide2.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            高校青年志愿服务组织是青年志愿队伍中最年轻、最积极、最具影响力的群体。志愿服务活动不仅是学生接触社会的重要渠道，也是高校全方位育人的重要途径。
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="/img/slide3.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            北京化工大学秉承着立足校园、服务他人、奉献社会、传播文明的宗旨，打造了一支优秀的志愿服务总队，用大学生志愿者的微笑和努力在社会播撒爱心和志愿的种子，不断推进志愿服务活动制度化、规范化、阵地化、社会化、品牌化。
                        </p>
                    </div>
                </div>

            </div> <a class="left carousel-control" href="#carousel-232573" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-232573" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
</div>
<!--中间幻灯片轮播-->


<div id="wrapper" style="padding:5%;">
    <div id="pager">

        <? foreach ($values as $value)?>

        <!--top -->
        <div class="zyd-main w-1000 cf">
            <!--tab -->
            <div class="zyd-tab mar-t20 mar-r20 f_l">
                <div id="fixed" style="position: relative; top: 0px;" class="">
                    <ul class="tabnav cf">
                        <li class="active">总队介绍</li>
                    </ul>
                </div>

                <!--tabcon -->
                <div class="tabcon" style="padding-top: 0px;">
                    <div class="ke-detail active">
                        <br/>

                        <p><?=$value['content']?>
                        </p>

                    </div>

                </div>
                <!--tabcon -->
            </div>
            <!--tab -->

            <!---aside -->
            <div class="zyd-aside mar-t20 f_r">
                <h3 class="caption">全称</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['full_name']?></span>
                        </div>
                    </li>
                </ul>

                <h3 class="caption">口号</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['slogan']?></span>
                        </div>
                    </li>
                </ul>
                <h3 class="caption">组成</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['compose']?></span>
                        </div>
                    </li>
                </ul>
                <h3 class="caption">宗旨</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['aim']?></span>
                        </div>
                    </li>
                </ul>
                <h3 class="caption">建设方针</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <span class="desc"><?=$value['constr_policy']?></span>
                        </div>
                    </li>
                </ul>

            </div>
            <!--aside -->
        </div>

    </div>
</div>

<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>