<?php
function menu_link($txt, $link, $act = ''){
	$act || $act = $link;
	echo '<li', false === stripos($_SERVER['REQUEST_URI'], $act)? '': ' class="active"', '><a href="', $link, '">', $txt, '</a></li>';
}
?>
<!DOCTYPE html>
<!--[if IE 8]><html lang="en" class="ie8 no-js"><![endif]-->
<!--[if IE 9]><html lang="en" class="ie9 no-js"><![endif]-->
<!--[if !IE]><html lang="en" class="no-js"><!--<![endif]-->
<head>
	<meta charset="utf-8"/>
	<title><?=$h1?><?=$h1msg?></title>
	<meta content="<?=$description?>" name="description"/>
	<meta content="<?=$keywords?>" name="keywords"/>
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN THEME STYLES -->
	<link href="/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="/assets/css/custom.css" rel="stylesheet" type="text/css"/>
	<!-- END THEME STYLES -->

	<link rel="shortcut icon" href="/favicon.ico"/>
	<script src="/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="/static/js/wvke.js" type="text/javascript"></script>
	<script src="/assets/scripts/Admin.Ajax.v1.0.js?v=1.05" type="text/javascript"></script>
</head>

<body class="page-header-fixed page-sidebar-fixed page-footer-fixed">

<!--头部-->
<div class="header navbar navbar-inverse navbar-fixed-top">
	<div class="header-inner">
		<a class="navbar-brand" href="#">一起志愿吧</a>
		<a href="#" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<img src="/assets/img/menu-toggler.png" alt=""/>
		</a>
		<ul class="nav navbar-nav pull-right">
			<li class="dropdown user">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<img src="/assets/img/face_default.png" width="20" height="20"/>
					<span class="username"><? echo $this->user['username']; ?></span>
					<i class="icon-angle-down"></i>
				</a>
				<ul class="dropdown-menu">
					<li><a href="/user/admin/userview/uid/<?=$user['id']?>"><i class="icon-user"></i> 个人资料</a></li>
					<li class="divider"></li>
					<li><a id="trigger_fullscreen"><i class="icon-move"></i> 全屏</a></li>
					<li><a href="/volunteer/logout"><i class="icon-signout"></i> 退出</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<!--头部-->

<div class="clearfix"></div>

<!--页面内容开始-->
<div class="page-container">
	<div class="page-sidebar navbar-collapse collapse">
		<ul class="page-sidebar-menu">
			<li>
				<div class="sidebar-toggler hidden-sm hidden-xs"></div>
			</li>

			<li>
				<form class="sidebar-search" method="POST" action="">
<!--				<form class="sidebar-search" method="POST" action="/admin/index/search/">-->
					<div class="form-container">
						<div class="input-box btn-group">
							<input type="text" autocomplete="off" id="kw" name="kw" placeholder="Search..." data-hover="dropdown" data-toggle="dropdown" class="dropdown-toggle"/>
							<ul role="menu" class="dropdown-menu">
<!--								<li><a onclick="Search('u.uid')">用户 > UID</a></li>-->
<!--								<li class="divider"></li>-->
<!--								<li><a onclick="Search('u.mobile')">用户 > 手机号</a></li>-->
							</ul>
							<input type="button" class="submit" value=" "/>
						</div>
					</div>
				</form>

			</li>

			<li class="start<? if (stripos($_SERVER['REQUEST_URI'], 'admin/index/index')) echo ' active' ?>">
				<a href="/admin/index/index/">
					<i class="icon-home"></i><span class="title">控制面板</span><span class="selected"></span>
				</a>
			</li>

			<li<? if (stripos($_SERVER['REQUEST_URI'], '/admin/introduce/list')) echo ' class="active"' ?>>
				<a>
					<i class="icon-group"></i><span class="title">总队简介管理</span><span class="arrow"></span>
				</a>
				<ul class="sub-menu">
					<? menu_link('总队简介', '/admin/introduce/list') ?>
<!--					--><?// menu_link('用户添加', '/user/admin/useradd/') ?>
				</ul>
			</li>

			<li<? if (stripos($_SERVER['REQUEST_URI'], '/admin/base/list')) echo ' class="active"' ?>>
				<a>
					<i class="icon-comment"></i>
					<span class="title">基地管理</span>
					<span class="arrow"></span>
				</a>
				<ul class="sub-menu">
					<? menu_link('基地列表', '/admin/base/list') ?>
                    <? menu_link('基地添加', '/admin/base/add') ?>
				</ul>
			</li>
			<li<? if (stripos($_SERVER['REQUEST_URI'], 'member')) echo ' class="active"' ?>>
				<a>
					<i class="icon-user"></i>
					<span class="title">会员管理</span>
					<span class="arrow"></span>
				</a>
				<ul class="sub-menu">
					<? menu_link('会员列表', '/admin/member/list') ?>
                    <? menu_link('会员添加', '/admin/member/add') ?>
				</ul>
			</li>

            <li<? if (stripos($_SERVER['REQUEST_URI'], 'volunteer')) echo ' class="active"' ?>>
                <a>
                    <i class="icon-user"></i>
                    <span class="title">志愿者管理</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <? menu_link('志愿者列表', '/admin/volunteer/list') ?>
                    <? menu_link('志愿者添加', '/admin/volunteer/add') ?>
                </ul>
            </li>

            <li<? if (stripos($_SERVER['REQUEST_URI'], 'discuss')) echo ' class="active"' ?>>
                <a>
                    <i class="icon-user"></i>
                    <span class="title">志愿者分享文章管理</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <? menu_link('文章列表', '/admin/discuss/list') ?>
                </ul>
            </li>

            <li<? if (stripos($_SERVER['REQUEST_URI'], 'activity')) echo ' class="active"' ?>>
                <a>
                    <i class="icon-user"></i>
                    <span class="title">志愿活动管理</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <? menu_link('活动列表', '/admin/activity/list') ?>
                    <? menu_link('活动添加', '/admin/activity/add') ?>
                </ul>
            </li>


		</ul>
	</div>
	<div class="page-content">
		<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
						<h4 class="modal-title"></h4>
					</div>
					<div class="modal-body"></div>
					<div class="modal-footer">
						<button type="button" class="btn blue">保存</button>
						<button type="button" class="btn default" data-dismiss="modal">关闭</button>
					</div>
				</div>
			</div>
		</div>
		<div class="theme-panel hidden-xs hidden-sm">
			<div class="toggler"></div>
			<div class="toggler-close"></div>
			<div class="theme-options">
				<div class="theme-option theme-colors clearfix">
					<span>主题颜色</span>
					<ul>
						<li class="color-black current color-default" data-style="default"></li>
						<li class="color-blue" data-style="blue"></li>
						<li class="color-brown" data-style="brown"></li>
						<li class="color-purple" data-style="purple"></li>
						<li class="color-grey" data-style="grey"></li>
						<li class="color-white color-light" data-style="light"></li>
					</ul>
				</div>
				<div class="theme-option">
					<span>布局</span>
					<select class="layout-option form-control input-small">
						<option value="fluid" selected="selected">自适应</option>
						<option value="boxed">固定宽度</option>
					</select>
				</div>
				<div class="theme-option">
					<span>头部</span>
					<select class="header-option form-control input-small">
						<option value="fixed" selected="selected">跟随</option>
						<option value="default">普通</option>
					</select>
				</div>
				<div class="theme-option">
					<span>菜单</span>
					<select class="sidebar-option form-control input-small">
						<option value="fixed">跟随</option>
						<option value="default" selected="selected">普通</option>
					</select>
				</div>
				<div class="theme-option">
					<span>页脚</span>
					<select class="footer-option form-control input-small">
						<option value="fixed">跟随</option>
						<option value="default" selected="selected">普通</option>
					</select>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<h3 class="page-title">
					<?=$h1?>
					<? if ($h1msg) echo '<small>', $h1msg, '</small>' ?>
				</h3>

				<ul class="page-breadcrumb breadcrumb">
					<li class="btn-group">
						<? if (isset($search)) { ?>
							<form id="form-search">
								<div class="row">
									<div class="col-md-12">
										<div class="input-group input-large">
											<input type="text" placeholder="搜索" class="form-control" name="kw" value="<?=empty($_GET['kw'])? '': $_GET['kw']?>">

											<div class="input-group-btn">
												<button tabindex="-1" class="btn dark" type="submit"><?=isset($search[$_GET['field']])? $search[$_GET['field']]: $_GET['field']?></button>
												<button tabindex="-1" data-toggle="dropdown" class="btn dark dropdown-toggle" type="button">
													<i class="icon-angle-down"></i></button>
												<ul role="menu" class="dropdown-menu">
													<? foreach ($search as $k1 => $v1) { ?>
														<li>
															<a onclick="$('#field').val('<?=$k1?>');$('#form-search').submit()"><?=$v1?></a>
														</li>
													<? } ?>
												</ul>
											</div>
											<input type="hidden" id="field" name="field" value="<?=$_GET['field']?>"/>
										</div>
									</div>
								</div>
							</form>
						<? } else { ?>
							<button type="button" class="btn blue dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
								<span>常用</span> <i class="icon-angle-down"></i>
							</button>
							<ul class="dropdown-menu pull-right" role="menu">
								<li class="divider"></li>
								<li><a href="/admin/activity/list">活动管理</a></li>
							</ul>
						<? } ?>
					</li>
					<li>
						<i class="icon-home"></i>
						<a href="/admin/index/index" target="_blank">主页</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="/admin/index/index/">后台</a>
						<i class="icon-angle-right"></i>
					</li>
					<li><a href="#"><?=$h1?></a></li>
				</ul>
			</div>
		</div>
		<div class="row margin-bottom-20">
			<div class="col-md-12">
				<?=$_content_?>
			</div>
		</div>
	</div>
</div>

<!--页面内容结束-->

<div class="footer">
	<div class="footer-inner">2017 &copy; volunteer.com</div>
	<div class="footer-tools"><span class="go-top"><i class="icon-angle-up"></i></span></div>
</div>

<!--[if lt IE 9]>
<script src="/assets/plugins/excanvas.min.js"></script>
<script src="/assets/plugins/respond.min.js"></script>
<![endif]-->
<script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
<script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="/assets/scripts/app.js"></script>
<script>jQuery(document).ready(function(){App.init()});</script>

</body></html>