<div role="grid" class="dataTables_wrapper form-inline">
	<table class="table table-striped table-bordered table-hover dataTable">
		<thead>
		<tr>
			<th>ID</th>
			<th>标题</th>
            <th>内容</th>
            <th>发布时间</th>
            <th>操作</th>

        </tr>
		</thead>
		<tbody id="table">
		<?
		foreach ($datas as $k1 => $v1) {?>
			<tr>
				<td><?=$v1['id']?></td>

				<td><?=mb_substr($v1['caption'],0,30)?></td>
                <td><?=mb_substr($v1['content'],0,20)?></td>
                <td><?=$v1['created_at']?></td>
				<td>
                    <a class="btn btn-xs red" onclick="discussdel(<?=$v1['id']?>)"><i class="icon-remove"></i> 删除</a>
				</td>
			</tr>
		<? } ?>
		</tbody>
	</table>
	<?= $page->show() ?>
</div>

<script>
    function discussdel(id){
        if(confirm('即将删除该行,操作不可恢复，是否继续？')) {
            $.post('/admin/discuss/del', {id: id}, function (d) {
                alert(d.msg);
                if (d.status) location.reload();
            }, 'json');
        }
    }
</script>