<a href="/admin/base/add/" class="btn green" href="#"><i class="icon-plus"></i>添加</a>
<div role="grid" class="dataTables_wrapper form-inline">
    <table class="table table-striped table-bordered table-hover dataTable">
        <thead>
        <tr>
            <th>ID</th>
            <th>基地名称</th>
            <th>基地简介</th>
            <th>创建时间</th>
            <th>更新时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody id="table">
        <?
        foreach ($datas as $k1 => $v1) {?>
            <tr>
                <td><?=$v1["id"]?></td>
                <td><?=$v1["base_name"]?></td>
                <td><?=mb_substr(strip_tags($v1['content']),0,15,'UTF-8')?></td>
                <td><?=$v1["created_at"]?></td>
                <td><?=$v1["updated_at"]?></td>
                <td>
                    <a class="btn btn-xs blue" href="/admin/base/edit/id/<?=$v1['id']?>"><i class="icon-edit"></i> 编辑</a>
                    <a class="btn btn-xs red" onclick="basedel(<?=$v1['id']?>)"><i class="icon-remove"></i> 删除</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
    <?= $page->show() ?>
</div>
<script>
    function basedel(id){
        if(confirm('即将删除该行,操作不可恢复，是否继续？')) {
            $.post('/admin/base/del', {id: id}, function (d) {
                alert(d.msg);
                if (d.status) location.reload();
            }, 'json');
        }
    }
</script>