<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 clearfix footer-col">
                <div class="footer-slogan">实现自我，志愿他人</div>

            </div>
            <div class="text-center">
                <div class="col-title">北京化工大学志愿服务总队</div>
                <a href="#" target="_blank">关于我们</a><br>
                <a href="#" target="_blank">联系我们</a><br>
                <a href="#" target="_blank">加入我们</a><br>
            </div>

        </div>

    </div>
    <div class="text-center copyright">
        <a href="http://zy.buct.edu.cn">Copyright@2009-2017 北京化工大学</a>
    </div>
</div>