<!--容器开始-->
<div class="container-flow">
    <!--基本导航条-->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        　<div class="navbar-header">
            　    <a href="/index" class="navbar-brand">一起志愿吧</a>
            　</div>
        <ul class="nav navbar-nav">
            <li><a href="##">志愿新闻</a></li>
            <li class="dropdown">
                <a href="##" data-toggle="dropdown" class="dropdown-toggle">志愿感悟</a>
                <ul class="dropdown-menu">
                    <li><a href="##">志愿心得</a></li>
                    <li><a href="##">志愿经历</a></li>
                    <li><a href="##">志愿体会</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="##" data-toggle="dropdown" class="dropdown-toggle">服务预告</a>
                <ul class="dropdown-menu">
                    <li><a href="##">志愿心得</a></li>
                    <li><a href="##">志愿经历</a></li>
                    <li><a href="##">志愿体会</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="##" data-toggle="dropdown" class="dropdown-toggle">志愿先锋</a>
                <ul class="dropdown-menu">
                    <li><a href="##">志愿心得</a></li>
                    <li><a href="##">志愿经历</a></li>
                    <li><a href="##">志愿体会</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="##" data-toggle="dropdown" class="dropdown-toggle">志愿基地</a>
                <ul class="dropdown-menu">
                    <li><a href="##">志愿心得</a></li>
                    <li><a href="##">志愿经历</a></li>
                    <li><a href="##">志愿体会</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="##" data-toggle="dropdown" class="dropdown-toggle">总队简介</a>
                <ul class="dropdown-menu">
                    <li><a href="##">志愿心得</a></li>
                    <li><a href="##">志愿经历</a></li>
                    <li><a href="##">志愿体会</a></li>
                </ul>
            </li>
            <li><a href="##">总队成员</a></li>
        </ul>
        <form action="##" class="navbar-form navbar-right" rol="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="志愿啦" />
            </div>
            <button type="submit" class="btn btn-default">立刻搜索</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="/user/login">登录</a></li>
            <li style="color:#fff;padding-top:14px;">|</li>
            <li><a href="/user/register">注册</a></li>
        </ul>

    </div><!--基本导航条-->

</div>
<!--1容器结束-->
