<div class="nk-bar"  style="padding: 7% 0 0 0;">
    <div class="module-box">
        <div class="module-head clearfix">
            <h1>榜单查看</h1>
        </div>
        <div class="module-body">
            <ul class="honor-rank-list">
                <li class="hrl-item"> <a href="/rank/ranking" class="hrl-ico hrl-a">全部榜单</a> </li>
                <li class="hrl-item"> <a href="/rank/detailday" class="hrl-ico hrl-c  link-green ">日排名</a> </li>
                <li class="hrl-item"> <a href="/rank/detailweek" class="hrl-ico hrl-c  link-green ">周排名</a> </li>
                <li class="hrl-item"> <a href="/rank/detailmonth" class="hrl-ico hrl-c  link-green ">月排名</a> </li>
                <li class="hrl-item"> <a href="/rank/detailquarter" class="hrl-ico hrl-c  link-green ">季排名</a> </li>
                <li class="hrl-item"> <a href="/rank/detailyear" class="hrl-ico hrl-c  link-green ">年排名</a> </li>
<!--                <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">学院排名</a> </li>-->
            </ul>
        </div>
    </div>
</div>