<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/discuss.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->

</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">

        <!--主体内容-->

        <div class="nk-content">
            <div class="module-box discuss-topic js-copy-mark" data-mark-info="hale">
                <div class="discuss-topic-head">
                    <?foreach ($datas as $k =>$v){?>

                    <h4 class="discuss-title"><?=$v['caption']?> </h4>
                    <div class="discuss-author clearfix">
<!--                        <a href="" class="answer-head" data-card-uid="826546" data-card-index="1"> </a>-->
                        <div class="post-detail">
                            <a> </a>
                            <a class="post-name level-color-9" href="" data-card-uid="826546" data-card-index="2"><?=$v['username']?></a>
                            <div class="post-legend">
                                <span class="post-time"> 编辑于 <?=$v['created_at']?> </span>
                                <div class="feed-legend">

                                    <form id="form-tags">
                                        <input type="hidden" name="share_id" value="<?=$v['id']?>">
                                        <input type="hidden" name="volunteer_id" value="<?=$this->user['id']?>">
                                        <input type="submit" class="js-post-like nc-req-auth" value="赞">
                                        <?=$v['tags']?>
                                    </form>

<!--                                    <span>浏览<span class="feed-legend-num">12717</span></span>-->

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="post-topic-main">
                    <div class="post-topic-des">
                        <?=$v['content']?>

                    </div>
                </div>
                <?}?>
            </div>
        </div>



        <div class="nk-bar">
            <div class="module-box column-nk">
                <div class="module-head clearfix">
                    <h1>愿吧专栏</h1>
                </div>
                <div class="module-body">
                    <ul class="column-nk-list">
                        <li> <a href="#"> <h4 class="column-nk-item column-nk-topic">每日话题</h4>
                                <div class="column-nk-txt">
                                    每天聊点儿有趣的
                                    <span class="column-nk-time">已结束</span>
                                </div> </a> </li>
                    </ul>
                </div>
            </div>

            <div class="nk-bar">
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>全站近期热帖</h1>
                    </div>
                    <div class="module-body">
                        <ul class="list-module">
                            <li>
                                <div class="list-title">
                                    <a class="list-name" href="#">一起志愿吧</a>
                                </div>
                                <div class="list-legend">发表于
                                    <a href="#"> 2015-04-20 20:53:42 </a>
                                </div> </li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>

    </div>
    <!--主体内容结束-->
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>


<script>WVKE.formsubmit('tags','/discuss/tags')</script>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>