<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/discuss.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">


        <!--主体内容-->
        <div class="nk-content">
            <div class="module-box">
                <div class="module-head clearfix">
                    <div class="module-head-oprt">
                        <a class="btn btn-primary btn-b-publish nc-req-auth" href="/discuss/share"> <i class="ico-submit"></i> 我要发布 </a>
                    </div>
                    <h2>分享与交流</h2>
                </div>
                <div class="tags-box tag-mod">
                    <a href="#" class="tag-label selected">全部</a>
                </div>
                <div class="menu-txt-box">
                    <ul class="menu-txt clearfix">
                        <li class="selected"> <a href="/discuss/share">最新发布</a> </li>
                    </ul>
                </div>
                <div class="module-body">
                    <ul class="common-list">
                        <li class="clearfix"> <a class="head-pic" data-card-uid="826546" href="#" data-card-index="1"></a>
                            <div class="discuss-detail">
                                <div class="discuss-main clearfix">
                                    <a href="#" target="_blank"> 【史上最有意义的活动】发面经，赢奖品！</a>
                                </div>
                                <div class="feed-foot">
                                    <div class="feed-origin">
                                        <p class="feed-tip"> <a class="d-name level-color-9" data-card-uid="826546" href="#" data-card-index="2"> 牛妹</a>&nbsp;&nbsp; 2017-04-20 &nbsp;&nbsp;发表 <a href="#"></a></p>
                                    </div>
                                    <div class="feed-legend">
                                        <span>赞<span class="feed-legend-num">4</span></span>
                                        <span class="feed-legend-pipe">|</span>
                                        <span>浏览<span class="feed-legend-num">6829</span></span>
                                    </div>
                                </div>
                            </div> </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--主体内容结束-->


        <div class="nk-bar">
            <div class="module-box column-nk">
                <div class="module-head clearfix">
                    <h1>愿吧专栏</h1>
                </div>
                <div class="module-body">
                    <ul class="column-nk-list">
                        <li> <a href="#"> <h4 class="column-nk-item column-nk-topic">每日话题</h4>
                                <div class="column-nk-txt">
                                    每天聊点儿有趣的
                                    <span class="column-nk-time">已结束</span>
                                </div> </a> </li>
                    </ul>
                </div>
            </div>

            <div class="nk-bar">
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>全站近期热帖</h1>
                    </div>
                    <div class="module-body">
                        <ul class="list-module">
                            <li>
                                <div class="list-title">
                                    <a class="list-name" href="#">一起志愿吧</a>
                                </div>
                                <div class="list-legend">发表于
                                    <a href="#"> 2015-04-20 20:53:42 </a>
                                </div> </li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>

    </div>
    <!--主体内容结束-->
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>