<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/discuss.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->
    <script type="text/javascript" src="/assets/model_editor/share_editor/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" src="/assets/model_editor/share_editor/ueditor/ueditor.all.js"></script>
    <script type="text/javascript" src="/assets/model_editor/share_editor/ueditor/lang/zh-cn/zh-cn.js"></script>



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">


        <!--主体内容-->
        <div class="module-box">
            <div class="module-head clearfix">
                <h1>
                    话题发布
                </h1>
            </div>

            <div class="module-body discuss-publish">

                <div class="topic-selected-box clearfix">

                    <div class="input-group">
                        <span class="input-group-addon" id="sizing-addon2">标题</span>
                        <input type="text" class="form-control" placeholder="一句话说明你想分享的经验" aria-describedby="sizing-addon2" style="width: 90%;">
                    </div>
                    <br>
                    <!--content 开始-->
                    <script type="text/plain" id="container"></script>
                    <script>
                        window.UEDITOR_CONFIG.savePath= ['upload/share'];
                        var editor = UE.getEditor('container');
                    </script>
                    <!--Content 结束-->
                </div>

                <div class="txtarea-foot clearfix"><div class="warning-tips" style="display:none;"></div>
                    <a href="javascript:void(0);" id="jsPublish" class="btn float-right btn-primary btn-modify-sure nc-req-auth click-pub-point">发布</a>
                    <a href="javascript:void(0);" id="jsCancel" class="btn btn-default float-right btn-modify-cancel">取消</a>
                </div>
            </div>
        </div>
    <!--主体内容结束-->
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>