<script type="text/javascript" src="/assets/plugins/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/assets/plugins/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/assets/plugins/ueditor/lang/zh-cn/zh-cn.js"></script>

<style>
    .top-news a {padding: 0px;TEXT-DECORATION:none}
</style>

<div class="col-md-12 news-page blog-page">
    <form method="post" action="/admin/introduce/edit" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-9 blog-tag-data">
                <div class="post-comment">

                    <div class="form-group">
                        <label class="control-label"><font><font>全称</font></font></label>
                        <input type="text" name="full_name" value="<?=$datas['full_name']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label"><font><font>口号</font></font></label>
                        <input type="text" name="slogan" value="<?=$datas['slogan']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label"><font><font>组成</font></font></label>
                        <input type="text" name="compose" value="<?=$datas['compose']?>" class="form-control" style="width: 50%"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label"><font><font>宗旨</font></font></label>
                        <input type="text" name="aim" value="<?=$datas['aim']?>" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label"><font><font>建设方针</font></font></label>
                        <input type="text" name="constr_policy" value="<?=$datas['constr_policy']?>" class="form-control" style="width: 50%"/>
                    </div>


                    <!--content 开始-->
                    <script type="text/plain" id="container"><?=$datas['content']?></script>
                    <script>
                        window.UEDITOR_CONFIG.savePath= ['upload/intro'];
                        var editor = UE.getEditor('container');
                    </script>
                    <!--Content 结束-->
                    <button class="btn blue margin-top-10" type="submit"><font><font>提交</font></font></button>
                </div>
            </div>

        </div>
        <input type="hidden" name="id"  value="<?=$datas['id']?>" />
    </form>
</div>
