<div role="grid" class="dataTables_wrapper form-inline">
	<table class="table table-striped table-bordered table-hover dataTable">
		<thead>
		<tr>
			<th>全称</th>
			<th>口号</th>
            <th>组成</th>
            <th>宗旨</th>
            <th>建设方针</th>
            <th>操作</th>

        </tr>
		</thead>
		<tbody id="table">
		<?
		foreach ($datas as $k1 => $v1) {?>
			<tr>
				<td><?=$v1['full_name']?></td>

				<td><?=$v1['slogan']?></td>
                <td><?=$v1['compose']?></td>
                <td><?=$v1['aim']?></td>
                <td><?=$v1['constr_policy']?></td>

				<td>
						<a class="btn btn-xs blue" href="/admin/introduce/edit/id/<?=$v1['id']?>"><i class="icon-edit"></i> 编辑</a>
				</td>
			</tr>
		<? } ?>
		</tbody>
	</table>
	<?= $page->show() ?>
</div>
