<style>
    .top-news a {padding: 0px;TEXT-DECORATION:none}
</style>
<div class="col-md-12 news-page blog-page">

    <form method="post" action="" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-9 blog-tag-data">

                <div class="post-comment">

                    <p>请选择要导入的CSV文件：
                        <br/>
                        <br/>
                        <input type="file" name="file">
                        <button class="btn blue margin-top-10" type="submit">导入CSV</button>

                </div>
            </div>

        </div>
    </form>


</div>
