<a href="/admin/member/add/" class="btn green" href="#"><i class="icon-plus"></i>添加</a>
<div role="grid" class="dataTables_wrapper form-inline">
    <table class="table table-striped table-bordered table-hover dataTable">
        <thead>
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>组别</th>
            <th>个人简介</th>
            <th>排序ID</th>
            <th>创建时间</th>
            <th>更新时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody id="table">
        <?
        foreach ($datas as $k1 => $v1) {?>
            <tr>
                <td><?=$v1["id"]?></td>
                <td><?=$v1["name"]?></td>
                <td>
                    <select onchange="membersave({id:<?=$v1['id']?>, group_id:this.value})">
                        <? foreach (MemberModel::$group_id as $k2 => $v2) { ?>
                            <option<? if ($v1['group_id'] == $k2) echo ' selected' ?> value="<?=$k2?>"><?=$v2?></option>
                        <? } ?>
                    </select>
                </td>
                <td><?=mb_substr(strip_tags($v1['content']),0,8,'UTF-8')?></td>
                <td>
                    <input onblur="membersave({id:<?=$v1['id']?>, sort_id:this.value})" type="text" value="<?=$v1['sort_id']?>" />
                </td>
                <td><?=$v1["created_at"]?></td>
                <td><?=$v1["updated_at"]?></td>
                <td>
                    <a class="btn btn-xs blue" href="/admin/member/edit/id/<?=$v1['id']?>"><i class="icon-edit"></i> 编辑</a>
                    <a class="btn btn-xs red" onclick="memberdel(<?=$v1['id']?>)"><i class="icon-remove"></i> 删除</a>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
    <?= $page->show() ?>
</div>
<script>
    function memberdel(id){
        if(confirm('即将删除该行,操作不可恢复，是否继续？')) {
            $.post('/admin/member/del', {id: id}, function (d) {
                alert(d.msg);
                if (d.status) location.reload();
            }, 'json');
        }
    }

    function membersave(data) {
        $.post('/admin/member/save', data, function (d) {
            alert(d.msg);
        }, 'json');
    }

</script>