<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/aboutUs.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">
        <!--主体内容-->
        <!--主体内容-->
        <div class="aboutus-main clearfix">
            <div class="aboutus-menu">
                <ul>
                    <li class="selected"><a href="/html/aboutus">关于我们</a></li>
                    <li><a href="/html/joinus">加入我们</a></li>
                    <li><a href="/html/contactus">联系我们</a></li>
                    <li><a href="/html/links">友情链接</a></li>
                </ul>
            </div>
            <div class="aboutus-content">
                <h1>关于我们</h1>
                <div class="aboutus-content-box">
                    <p>
                        北京化工大学志愿服务总队引导青年志愿者竭诚为广大同学服务，以“立足学校，服务社会，提高全校志愿者的综合素质，创造校园文化的和谐氛围，树立化工大学的良好形象，为构建和谐社会不懈努力”为奋斗目标，用实际行动诠释着“奉献、友爱、互助、进步”的志愿服务精神。
                    </p>
                    <p>
                        青年志愿服务活动经过多年的发展，奥运、国庆的志愿服务成果转化，现如今已遍布全国各大高校。从社会功效的角度出发，志愿服务是一种重要的社会整合机制，是社会保障体系的重要补充；从文化功效的角度出发，志愿服务是精神文明建设的可靠载体和有效形式，是公民道德教育的重要渠道。高校青年志愿服务组织是青年志愿队伍中最年轻、最积极、最具影响力的群体。志愿服务活动不仅是学生接触社会的重要渠道，也是高校全方位育人的重要途径。北京化工大学秉承着立足校园、服务他人、奉献社会、传播文明的宗旨，打造了一支优秀的志愿服务总队，用大学生志愿者的微笑和努力在社会播撒爱心和志愿的种子，不断推进志愿服务活动制度化、规范化、阵地化、社会化、品牌化。
                    </p>
                    <p>
                        校园是同学们平日生活中最熟悉的地方，我校立足校园，分别在东校区、北校区和西校区开展了丰富多彩的志愿服务活动，拓展校内服务阵地，让同学们从校内做起、从身边小事做起，锻炼服务技巧、提升服务热情、积累传播正能量，以将志愿的火种播撒在更多地方。
                    </p>
                    <p>
                        诚挚的奉献情怀和热忱的志愿精神，是化大志愿者的追求；广阔的青春舞台和系统的培训空间是我校志愿服务的特色。在学校党委和北京市志愿服务指导中心的正确领导下，在学校团委的悉心指导下，在各志愿服务基地的大力支持下，北京化工大学将继续在校内外广泛开展各种志愿活动，大力宣传和弘扬志愿服务精神，推动志愿服务事业常态发展、稳步前行。我们相信，在未来的日子里，我校的青年志愿者们一定能为社会各界提供更优质的服务、展现更灿烂的笑容，以志愿公益之心谱写我校志愿者永恒的青春华章，以服务奉献之行点亮神州大地的中国梦想！
                    </p>
                    <p>微信公众账号：buct_volunteer（北区）</p>
                    <p><img src="/img/buct_beiqu.jpeg" width="258" height="258"></p>
                    <p>微信公众账号：bhzyfw（东区）</p>
                    <p><img src="/img/buct.jpg" width="258" height="258"></p>
                    <p>官方微博：北京化工大学志愿服务总队</p>
                    <p><img src="/img/blog.jpg" width="258" height="258"></p>
                </div>
            </div>
        </div>
        <!--主体内容结束-->
    </div>
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>