<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/aboutUs.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->
</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">
        <!--主体内容-->
        <!--主体内容-->
        <div class="aboutus-main clearfix">
            <div class="aboutus-menu">
                <ul>
                    <li><a href="/html/aboutus">关于我们</a></li>
                    <li><a href="/html/joinus">加入我们</a></li>
                    <li class="selected"><a href="/html/contactus">联系我们</a></li>
                    <li><a href="/html/links">友情链接</a></li>
                </ul>
            </div>
            <div class="aboutus-content">
                <h1>联系我们</h1>
                <div class="aboutus-content-box">
                    <div class="aboutus-content-txt">
                        <p>东区地址</p>
                        <p>联系地址： 北京市朝阳区北三环东路15号北京化工大学22号信箱</p>
                        <p>联系邮编： 100029</p>
                        <p>联系电话： 010-64411322</p>
                        <p>联系邮箱： bhzyz@mail.buct.edu.cn; buctzyz@126.com</p>
                        <p>办公地址： 北京化工大学图书馆地下室志愿服务总队办公室</p>
                        <p>传真号码： 010-64432942</p>
                        <p>北区地址</p>
                        <p>联系地址： 北京市昌平区南环东路15号北京化工大学北区分团委</p>
                        <p>联系邮编： 102200</p>
                        <p>联系电话： 010—80104006</p>
                        <p>联系邮箱： buctvolunteer@163.com</p>
                        <p>办公地址： 北京化工大学（北区）主教学楼地下室D08志愿服务总队办公室</p>
                        <p>传真号码： 010—80117688</p>
                        <p>西区地址</p>
                        <p>联系地址： 北京市海淀区紫竹院路98号院教学楼217室</p>
                        <p>联系邮编： 100089</p>
                        <p>联系电话： 15011351276、15001251202</p>
                        <p>联系邮箱： buctxqzyfw@126.com</p>
                        <p>办公地址： 北京化工大学（西区）教学楼301室</p>
                        <p>传真号码： 西区传真(暂无)</p>
                    </div>
                </div>
            </div>
        </div>
        <!--主体内容结束-->

    </div>
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>