<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/aboutUs.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main clearfix">
        <!--主体内容-->
        <!--主体内容-->
        <div class="aboutus-main clearfix">
            <div class="aboutus-menu">
                <ul>
                    <li><a href="/html/aboutus">关于我们</a></li>
                    <li class="selected"><a href="/html/joinus">加入我们</a></li>
                    <li><a href="/html/contactus">联系我们</a></li>
                    <li><a href="/html/links">友情链接</a></li>
                </ul>
            </div>
            <div class="aboutus-content">
                <h1>加入我们</h1>
                <div class="aboutus-content-box">
                    <p>奉献</p>
                    <p>友爱</p>
                    <p>互助</p>
                    <p>进步</p>
                    <p>志愿者是无偿，不是开业、打工，而是不计报酬的；</p>
                    <p>志愿者不是救世主，而是与被帮助者处于平等、互相尊重的地位；</p>
                    <p>志愿者不仅是给予了他们帮助，同时也得到了收获——自我的一种成长；</p>
                    <p>志愿者的出发点不是好奇心的满足，而是对社会的回报；</p>
                    <p>志愿者不是指挥者、教育者，而是用生命去影响生命；</p>
                    <p>赶快加入我们吧。</p>
                    <p>邮箱：<a href="mailto:bhzyz@mail.buct.edu.cn">bhzyz@mail.buct.edu.cn</a> </p>
                    <p>联系方式：010-64411322</p>
                    <p>办公地点：北京化工大学图书馆地下室志愿服务总队办公室</p>
                </div>
            </div>
        </div>
        <!--主体内容结束-->

    </div>
</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>