<script type="text/javascript" src="/assets/model_editor/activity_editor/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/assets/model_editor/activity_editor/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/assets/model_editor/activity_editor/ueditor/lang/zh-cn/zh-cn.js"></script>

<style>
    .top-news a {padding: 0px;TEXT-DECORATION:none}
</style>
<div class="col-md-12 news-page blog-page">
    <form method="post" action="/admin/activity/edit" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-9 blog-tag-data">
                <div class="post-comment">

                    <div class="form-group">
                        <label class="control-label">活动名称</label>
                        <input type="text" name="caption" value="" class="form-control" style="width: 50%"/>
                    </div>

<!--                    <div class="form-group">-->
<!--                        <label class="control-label">开始时间</label>-->
<!--                        <input type="text" name="starttime" value="" class="form-control" style="width: 50%"/>-->
<!--                    </div>-->
<!---->
<!--                    <div class="form-group">-->
<!--                        <label class="control-label">结束时间</label>-->
<!--                        <input type="text" name="endtime" value="" class="form-control" style="width: 50%"/>-->
<!--                    </div>-->


                    <div class="form-group">
                        <label class="control-label" for="form_subway">上传活动封面：</label>
                        <input type="file" name="img[]"/>
                    </div>

                    <br/>
                    <label class="control-label">活动详情:</label>
                    <!--content 开始-->
                    <script type="text/plain" id="container"></script>
                    <script>
                        window.UEDITOR_CONFIG.savePath= ['upload/activity'];
                        var editor = UE.getEditor('container');
                    </script>
                    <!--Content 结束-->
                    <button class="btn blue margin-top-10" type="submit">提交</button>
                </div>
            </div>

        </div>
    </form>
</div>
