<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/profile.css"/>
    <link rel="stylesheet" href="/css/discuss.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->

    <link href="/assets/date/css/bootstrap-datetimepicker.min.css" rel="stylesheet">



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>
        <!--主体内容-->

<div class="nk-main profile-page clearfix">
            <div class="nk-bar">
                <div class="module-box side-profile-box">
                    <div class="side-profile-info">
                        <div class="side-profile-avatar">
                            <div class="side-profile-pic">
                                <img src="/img/1.jpg" height="100" width="100" id="avatarImage" />
                            </div>
                        </div>

                        <h3 class="side-profile-name level-color-7">个人密码</h3>
                    </div>
                    <div class="profile-count-box">
                        <a class="btn btn-primary" href="/index/index/">返回首页</a>
                        <a class="btn btn-primary" href="/volunteer/index">查看信息</a>
                    </div>

                </div>
            </div>

            <div class="nk-content">
                <div class="module-box profile-info">
                    <div class="menu-box" id="menubox">
                        <ul class="menu clearfix">
                            <li class="selected nc-req-auth"><a href="#">个人密码</a> </li>
                        </ul>
                    </div>

                    <div class="module-body">

                        <div class="profile-caption">
                            <h3 class="info-title prf-base">修改密码</h3>
                        </div>

                        <form id="form-changepw">
                        <div class="info-box">

                            <dl>
                                <dt>登录密码</dt>
                                <dd class="control-group" id="jsCpn_1_input_0">
                                    <input type="password" class="form-control" placeholder="请输入登录密码" name="pw" value="">
                                </dd>
                            </dl>

                            <dl>
                                <dt>新密码</dt>
                                <dd class="control-group" id="jsCpn_1_input_1">
                                    <input type="password" class="form-control" placeholder="请输入新密码" name="newpw" value="">
                                </dd>
                            </dl>

                            <dl>
                                <dt>确认密码</dt>
                                <dd class="control-group" id="jsCpn_1_input_2">
                                    <input type="password" class="form-control" placeholder="请再次输入新密码" name="re_newpw" value="">
                                </dd>
                            </dl>


                        </div>

                        <div class="txtarea-foot clearfix"><div class="warning-tips" style="display:none;"></div>

                            <input type="submit" class="btn float-right btn-primary btn-modify-sure nc-req-auth click-pub-point" value="确认">
                            <a href="/volunteer/index" id="jsCancel" class="btn btn-default float-right btn-modify-cancel">取消</a>
                        </div>

                    </div>
                </form>


                </div>
            </div>
</div>
        <!--主体内容结束-->
<script>WVKE.formsubmit('changepw')</script>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script type="text/javascript" src="/assets/date/jquery/jquery-1.8.3.min.js" charset="UTF-8"></script>
<script type="text/javascript" src="/assets/date/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/date/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script type="text/javascript" src="/assets/date/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>

<script type="text/javascript">

    $('.birthday').datetimepicker({
        language:  'zh-CN',
        format: "yyyy-mm-dd",
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        minView: 2,
        maxView: 4,
        forceParse: 0,
        pickerPosition: "bottom-left"
    });
</script>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>