<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/profile.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>
        <!--主体内容-->

<div class="nk-main profile-page clearfix">
            <div class="nk-bar">
                <div class="module-box side-profile-box">
                    <div class="side-profile-info">
                        <div class="side-profile-avatar">
                            <div class="side-profile-pic">
                                <img src="/img/1.jpg" height="100" width="100" id="avatarImage" />
                            </div>
                        </div>
                        <?foreach ($datas as $k1 => $v1){?>
                        <h3 class="side-profile-name level-color-7"><?=$v1['username']?></h3>
                    </div>
                    <div class="profile-count-box">
                        <a class="btn btn-primary" href="/index/index/">返回首页</a>
                        <a class="btn btn-primary" href="/volunteer/edit">编辑信息</a>
                    </div>

                </div>
            </div>
            <div class="nk-content">
                <div class="module-box profile-info">
                    <div class="menu-box" id="menubox">
                        <ul class="menu clearfix">
                            <li class="selected nc-req-auth"><a href="#">个人信息</a> </li>
                        </ul>
                    </div>
                    <div class="module-body">
                        <!-- 基本信息 -->
                        <div class="profile-info-box" id="basicInfo">


                            <div class="profile-caption">
                                <h3 class="info-title prf-base">基本信息</h3>
                            </div>
                            <div class="info-box set-msg-box">
                                <dl>
                                    <dt>
                                        我的姓名
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['username']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        我的性别
                                    </dt>
                                    <dd>
                                        <span>
                                            <? foreach (VolunteerModel::$sex as $k2 => $v2) { ?>
                                                <? if ($v1['sex'] == $k2) echo $v2;?>
                                            <?}?>
                                        </span>
                                    </dd>
                                </dl>

                                <dl>
                                    <dt>
                                        我的班级
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['class']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        我的学号
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['student_id']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        我的学院
                                    </dt>
                                    <dd id="nicknamePart">

                                        <? foreach (VolunteerModel::$academy as $k2 => $v2) { ?>
                                            <? if ($v1['academy_id'] == $k2) echo $v2;?>
                                        <?}?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        我的民族
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['nation']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        我的生日
                                    </dt>
                                    <dd>
                                        <?=mb_substr($v1['birthday'],0,10)?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        我的籍贯
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['origin']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        政治面貌
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['political_status']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        个人邮箱
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['email']?>
                                    </dd>
                                </dl>
                                <dl>
                                    <dt>
                                        个人电话
                                    </dt>
                                    <dd id="nicknamePart">
                                        <?=$v1['mobile']?>
                                    </dd>
                                </dl>


                                <dl>
                                    <dt>
                                        我的简介
                                    </dt>
                                    <dd id="introductionPart">
                                        <?=$v1['content']?>
                                    </dd>
                                </dl>

                            </div>

<!--                            <div class="profile-caption">-->
<!--                                <h3 class="info-title prf-base">志愿信息</h3>-->
<!--                            </div>-->
<!---->
<!--                            <div class="info-box set-msg-box">-->
<!--                                个人所做志愿活动-->
<!--                            </div>-->

                        <?}?>
                        </div>
                    </div>
                </div>
            </div>
</div>
        <!--主体内容结束-->

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>