<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>用户登录</title>
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/login.css">

    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>

</head>

<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<!--login----content-->
<div class="container interval">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">

<!--            提交表单信息开始-->
            <form id="form-login" class="form-horizontal">

                <div class="form-group">
                    <label for="studentid">学号</label>
                    <input type="text" class="form-control" id="studentid" name="studentid" placeholder="请输入学号">
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码">
                </div>
                <div class="form-group">
                    <div class="keep-pwd checkbox">
                        <label>
                            <input type="checkbox"> 记住密码
                        </label>
                        <a href="#" class="forget-pwd" style="text-decoration: none;">忘记密码？</a>
                    </div>

                </div>
                <input type="submit" class="btn btn-success btn-block" value="立即登录">
            </form>

<!--            提交表单结束-->
        </div>
        <div class="col-md-4"></div>
    </div>

</div>
<script>WVKE.formsubmit('login')</script>


<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->
<!--代码-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>


</body>
</html>