<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>用户注册</title>
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/register.css">


    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>

</head>

<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<!--register----content-->
<div class="container interval">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">

<!--            提交表单开始-->
            <form id="form-register" class="form-horizontal">
                <div class="form-group">
                    <label for="username">姓名</label>
                    <input type="text" class="form-control" name="username" placeholder="请输入真实姓名">
                </div>
                <div class="form-group">
                    <label for="username">学号</label>
                    <input type="text" class="form-control" name="studentid" placeholder="请输入学号">
                </div>
                <div class="form-group">
                    <label for="mobile">手机号</label>
                    <input type="text" class="form-control" name="mobile" placeholder="请输入手机号">
                </div>
                <div class="form-group">
                    <label for="email">邮箱</label>
                    <input type="email" class="form-control" name="email" placeholder="请输入邮箱">
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" name="password" placeholder="请输入密码">
                </div>
                <div class="form-group">
                    <label for="re_password">重输密码</label>
                    <input type="password" class="form-control" name="re_password" placeholder="请重复输入密码">
                </div>
                <input type="submit" class="btn btn-success btn-block" value="立即注册">
            </form>
<!--            提交表单结束-->
        </div>
        <div class="col-md-4"></div>
    </div>

</div>

<script>WVKE.formsubmit('register')</script>

<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->
<!--代码-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>


</body>
</html>