<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>jQuery Tilted Page Scroll by Pete R. | The Pete Design</title>
    <meta name="title" content="jQuery One Page Scroll by Pete R. | The Pete Design" />
    <meta name="description" content="Create a beautiful 3D tilted effect on scroll with jQuery Tilted Page Scroll plugin by Pete Rojwongsuriya" />

    <meta name="author" content="Pete R.">
    <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery.tiltedpage-scroll.js"></script>
    <link href='/css/tiltedpage-scroll.css' rel='stylesheet' type='text/css'>
    <link href='/css/3d.css' rel='stylesheet' type='text/css'>
    <script>
        $(document).ready(function(){
            $(".main").tiltedpage_scroll({
                angle: 10
            });
        });

    </script>
</head>
<body>

<div class="wrapper">
    <div class="main">
        <div class="header">
            <h1>jQuery Tilted Page Scroll</h1>
            <h2>Create a 3D Tilted Scroll Effect with jQuery Tilted Page Scroll Plugin</h2>


        </div>
        <section class="page1">
            <div class="page_container">
                <h1><a href="#" target="_blank">Travel to Sydney, Australia<br><small>Completed on 14 Feb 2014</small></a></h1>

            </div>
        </section>
        <section class="page2">
            <div class="page_container">
                <h1><a href="#" target="_blank">Visit Uluru (Ayers Rock), Australia<br><small>Completed on 17 Feb 2014</small></a></h1>
            </div>
        </section>
        <section class="page3">
            <div class="page_container">
                <h1><a href="#" target="_blank">Travel to ZhangJiaJie (Avatar's Mountain) in China<br><small>Completed on 20 Jan 2014</small></a></h1>
            </div>
        </section>
        <section class="page4">
            <div class="page_container">
                <h1><a href="#" target="_blank">Ride a Camel in the Australian Outback<br><small>Completed on 17 Feb 2014</small></a></h1>
            </div>
        </section>
        <section class="page5">
            <div class="page_container">
                <h1><a href="#" target="_blank">Travel to Sydney, Australia<br><small>Completed on 14 Feb 2014</small></a></h1>
            </div>
        </section>
        <section class="page6">
            <div class="page_container">
                <h1><a href="#" target="_blank">Visit Uluru (Ayers Rock), Australia<br><small>Completed on 17 Feb 2014</small></a></h1>
            </div>
        </section>
        <section class="page7">
            <div class="page_container">
                <h1><a href="#" target="_blank">Travel to ZhangJiaJie (Avatar's Mountain) in China<br><small>Completed on 20 Jan 2014</small></a></h1>
            </div>
        </section>
        <section class="page8">
            <div class="page_container">
                <h1><a href="#" target="_blank">Ride a Camel in the Australian Outback<br><small>Completed on 17 Feb 2014</small></a></h1>
            </div>
        </section>
    </div>

</div>

<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->

</body>
</html>