<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>活动详情</title>
    <meta name="keywords" content="hello" />
    <meta name="description" content="hello" />
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/common.css" />
    <link rel="stylesheet" href="/css/detail.css" />

    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>


</head>
<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->
<div id="wrapper" style="padding:5%;">
    <div id="pager">
        <div class="zyd-top w-1000 cf">
            <div class="media f_l">
                <img src="<?=$value['img']?>"/>
            </div>
            <ul class="explain f_r">
                <li class="author"></li>
                <li class="intor"></li>
                <li class="price">
                    <span class="curr-price"><?=$value['caption']?></span>
                </li>

                <li class="cf last">

<!--                    报名按钮-->
                    <form id="form-activitydetail">
                       <input type="hidden" name="activity_id" value="<?=$value['id']?>">
                        <input type="hidden" name="volunteer_id" value="<?=$this->user['id']?>">

                        <?

                        $day = (strtotime($value['end_time']) - time())/(24*3600);
                        $day = floor($day);
                        $condition = $day;

                        $num = $value['limit_num'] - $value['already_num'];

                        if(($condition>1 || $condition == 1) && ($num != 0)){?>
                                <input type="submit" class="greenbtn2" value="立即报名">
                        <?}else if(0 == $condition || ($num == 0 ) && ($condition>1 || $condition == 1)){?>
                            <input type="submit"  class="greenbtn1" value="暂停报名" disabled>
                        <?}else{?>
                            <input type="submit" class="greenbtn3" value="已经结束" disabled>
                        <?}?>

                    </form>
<!--                    报名按钮-->

                    <?
                    $day = (strtotime($value['end_time']) - time())/(24*3600);
                    $day = floor($day);
                    $condition = $day;

                    $num = $value['limit_num'] - $value['already_num'];
                    if(($condition>1 || $condition == 1)&& ($num != 0)){?>
                        <p class="time">
                            <span>目前<?=$value['already_num']?>人报名</span>
                            <span>服务时长：<?=$value['service_hour']?> 小时</span>
                            <span>距离报名截止还有：
                                <?=$condition?>
                                天
                        </span>
                        </p>

                    <?}else if(0 == $condition || ($num == 0 ) && ($condition>1 || $condition == 1)){?>
                        <p class="time">
                            <span>目前<?=$value['already_num']?>人报名</span>
                            <span>服务时长：<?=$value['service_hour']?> 小时</span>
                        </p>

                    <?}else{?>
                        <p class="time">
                            <span>该活动已经结束，快去选择其他志愿活动参加吧！</span>
                        </p>

                    <?}?>

                </li>
            </ul>
        </div>
        <!--top -->
        <div class="zyd-main w-1000 cf">
            <!--tab -->
            <div class="zyd-tab mar-t20 mar-r20 f_l">
                <div id="fixed" style="position: relative; top: 0px;" class="">
                    <ul class="tabnav cf">
                        <li class="active">活动详情</li>
                    </ul>
                </div>
                <!--tabcon -->
                <div class="tabcon" style="padding-top: 0px;">
                    <div class="ke-detail active">
                        <p> <?=$value['content']?></p>

                    </div>

                </div>
                <!--tabcon -->
            </div>
            <!--tab -->

            <!---aside -->
            <div class="zyd-aside mar-t20 f_r">
                <h3 class="caption">志愿口号</h3>
                <ul class="list">
                    <li>
                        <p class="intor">青春北化，志愿你我</p> </li>
                </ul>
            </div>
            <!--aside -->

        </div>
    </div>
</div>
<script>WVKE.formsubmit('activitydetail')</script>
    <!--foot start-->
    <?php include PATH_TPL.'/foot.phtml'?>
    <!--foot end-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>