<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>活动详情</title>
    <meta name="keywords" content="hello" />
    <meta name="description" content="hello" />
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/common.css" />
    <link rel="stylesheet" href="/css/detail.css" />
</head>
<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->
<div id="wrapper" style="padding:5%;">
    <div id="pager">
        <div class="zyd-top w-1000 cf">
            <div class="media f_l">
                <img src="<?=$value['img']?>" alt="志愿的详情" />
            </div>
            <ul class="explain f_r">
                <li> <h1> <?=$value['name']?> </h1> <i class="icon-tag-yellow">新</i> </li>
                <li class="author"><?=$value['desc']?></li>
                <li class="intor"><?=$value['desc']?></li>
                <li class="price">
                    <span class="curr-price"><?=$value['desc']?></span>
                    <span class="vip-price"><?=$value['desc']?></span>
                </li>
                <li class="cf last">
                    <a class="greenbtn2" href="#" style="text-decoration: none;" data-zhiye-id="">立即报名</a>
                    <p class="time">
                        <span>目前<?=$value['already_num']?>人报名</span>
                        <span>志愿时长：<?=$value['service_hour']?> 小时</span>
                        <span>有效期：10 天</span>
                    </p>
                </li>
            </ul>
        </div>
        <!--top -->
        <div class="zyd-main w-1000 cf">
            <!--tab -->
            <div class="zyd-tab mar-t20 mar-r20 f_l">
                <div id="fixed" style="position: relative; top: 0px;" class="">
                    <ul class="tabnav cf">
                        <li class="active">志愿详情</li>
                    </ul>
                </div>
                <!--tabcon -->
                <div class="tabcon" style="padding-top: 0px;">
                    <div class="ke-detail active">
                        <p> <?=$value['details']?></p>

                    </div>

                </div>
                <!--tabcon -->
            </div>
            <!--tab -->

            <!---aside -->
            <div class="zyd-aside mar-t20 f_r">
                <h3 class="caption">志愿主题</h3>
                <ul class="list">
                    <li>
                        <div class="teacher cf">
                            <!--  <a class="headpic" href="javascript:;"> <img src="./detail/0v6h3v76678xx.jpeg" alt="" /> </a>
                             <h2 class="tit"><a href="javascript:;">江小鱼</a></h2>
                             <span class="desc">极客学院布道师</span>  -->
                        </div> <p class="intor">为更好促进家庭文化建设，传承志愿服务精神；更好的服务特困儿童家庭和特困单身母亲家庭，建立互助互爱的和谐社区；打造崇义友善的大美朝阳。朝阳区妇联联合辖区内各街乡社区居民将在国际家庭日期间筹备第六届家庭文化艺术节启动仪式暨区级最美家庭揭晓活动。</p> </li>
                </ul>
            </div>
            <!--aside -->

        </div>
    </div>
</div>
    <!--foot start-->
    <?php include PATH_TPL.'/foot.phtml'?>
    <!--foot end-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>