<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>首页</title>

<!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
<!--        head foot样式必须css文件-->

    <link rel="stylesheet" href="/css/shover.css">

<!--    粗发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        粗发提交的js插件--必须-->

    <script src="/js/sHover.min.js"></script>

    <script>
        window.onload=function(){
            var allItem=new sHover("beforeIn","afterIn");
            allItem.set({
                slideSpeed:5,
                opacityChange:true,
                opacity:80
            });

        }
    </script>
</head>

<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<!--中间幻灯片轮播-->
<div class="row">
    <div class="col-md-12 column">
        <div class="carousel slide" id="carousel-232573">
            <ol class="carousel-indicators">
                <li data-slide-to="0" data-target="#carousel-232573" class="active">
                </li>
                <li data-slide-to="1" data-target="#carousel-232573">
                </li>
                <li data-slide-to="2" data-target="#carousel-232573">
                </li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img alt="" src="/img/slide1.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            这次志愿者服务的经历也对我的人生产生了重大的影响。作为在学校里的学生、作为在社会里的个人，我们也应该学会服从、付出、充满热情。在接下来的日子里，我会继续努力，以党员的要求来要求自己，不断地完善自己，积极为人民服务。
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="/img/slide2.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            这次志愿者服务的经历也对我的人生产生了重大的影响。作为在学校里的学生、作为在社会里的个人，我们也应该学会服从、付出、充满热情。在接下来的日子里，我会继续努力，以党员的要求来要求自己，不断地完善自己，积极为人民服务。
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="/img/slide3.jpg" />
                    <div class="carousel-caption">
                        <h4>
                            我们一起做志愿
                        </h4>
                        <p>
                            这次志愿者服务的经历也对我的人生产生了重大的影响。作为在学校里的学生、作为在社会里的个人，我们也应该学会服从、付出、充满热情。在接下来的日子里，我会继续努力，以党员的要求来要求自己，不断地完善自己，积极为人民服务。
                        </p>
                    </div>
                </div>

            </div> <a class="left carousel-control" href="#carousel-232573" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-232573" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
</div>
<!--中间幻灯片轮播-->

<!--中间标题-->
<div style="text-align:center;">
    <h3>志愿服务活动列表</h3>
</div>
<!--中间标题-->
<!--活动列表开始-->
<div class="container">
    <!--缩略图列表开始-->
    <div class="row">
        <? foreach ($datas as $v){?>
        <div class="col-xs-6 col-md-3 beforeIn">

            <a href="#" class="thumbnail">
                <img src="<?=$v['img']?>" style="height: 180px; width: 100%; display: block;" alt="">
            </a>

            <div class="caption afterIn">
                <h2><?=$v['name']?></h2>
                <p><?=$v['desc']?></p>
                <p>
                    <a href="/index/index/activitydetail/id/<?=$v['id']?>" class="btn btn-primary">立即报名</a>
                </p>
                <p>计划招募：<?=$v['limit_num']?>人 | 已经招募：<?=$v['already_num']?>人</p>

            </div>
        </div>
        <?}?>
    </div>
</div>
<?=$page->show()?>

<!--缩略图列表结束-->
<!--活动列表开始-->

<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->
<!--代码-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>


</body>
</html>