<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>首页</title>

<!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
<!--        head foot样式必须css文件-->

<!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
<!--        列表浮动显示-->

<!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        粗发提交的js插件--必须-->


    <script>
        window.onload=function(){
            var allItem=new sHover("beforeIn","afterIn");
            allItem.set({
                slideSpeed:5,
                opacityChange:true,
                opacity:80
            });

        }
    </script>
</head>

<body>
<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<!--中间标题-->
<div style="text-align:center;">
    <h3>志愿服务活动列表</h3>
</div>
<!--中间标题-->
<!--活动列表开始-->
<div class="container">
    <!--缩略图列表开始-->
    <div class="row">
        <? foreach ($datas as $v){?>
        <div class="col-xs-6 col-md-3 beforeIn">

            <a href="#" class="thumbnail">
                <img src="<?=$v['img']?>" style="height: 180px; width: 100%; display: block;" alt="">
            </a>

            <div class="caption afterIn">
                <h2><?=$v['caption']?></h2>
                <p>
                    <a href="/index/index/activitydetail/id/<?=$v['id']?>" class="btn btn-primary">我要报名</a>
                </p>
                <p>计划招募：<?=$v['limit_num']?>人 | 已经招募：<?=$v['already_num']?>人</p>

            </div>
        </div>
        <?}?>
    </div>
</div>
<!--分页-->
<?=$page->show()?>

<!--缩略图列表结束-->
<!--活动列表开始-->

<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->
<!--代码-->
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>


</body>
</html>