<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/honor.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main topic-main honor-main clearfix">
        <!--主体内容-->
        <div class="nk-content"  style="padding: 7% 0 0 0;">
            <div class="module-box">
                <div class="module-head clearfix">
                    <h1>日排名</h1>
                </div>
                <div class="module-body">
                    <div class="menu-box">
                        <ul class="menu clearfix">
                            <li class="selected"> <a href="javascript:void(0);">总榜</a> </li>
                        </ul>
<!--                        <span class="exercise-result"> 你的登录天数： 6 | 排名： 3990 </span>-->
                    </div>
                    <table>
                        <tbody>
                        <tr>
                            <th width="80">排名</th>
                            <th width="120">用户</th>
                            <th width="280">个性签名</th>
                            <th width="80">志愿时间</th>
                        </tr>
                        <tr>
                            <td> <span class="browse-num top-browse top1"> 1 </span> </td>
                            <td class="txt-left">
                                <div class="nker-info">
                                    <a class="nker-name level-color-6" data-card-uid="1724" href="https://www.nowcoder.com/profile/1724" data-card-index="2"> 毛坚持 </a>
                                </div> </td>
                            <td> ╮(╯▽╰)╭暂无签名 </td>
                            <td class="js-follow-count"> 541 </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="nk-bar"  style="padding: 7% 0 0 0;">
            <div class="module-box">
                <div class="module-head clearfix">
                    <h1>榜单查看</h1>
                </div>
                <div class="module-body">
                    <ul class="honor-rank-list">
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-a">全部榜单</a> </li>
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">日排名</a> </li>
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">周排名</a> </li>
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">月排名</a> </li>
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">季排名</a> </li>
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">年排名</a> </li>
                        <li class="hrl-item"> <a href="#" class="hrl-ico hrl-c  link-green ">学院排名</a> </li>
                    </ul>
                </div>
            </div>
        </div>


</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>