<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/honor.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main topic-main honor-main clearfix">
        <!--主体内容-->
        <div class="nk-content"  style="padding: 7% 0 0 0;">
            <div class="module-box">
                <div class="module-head clearfix">
                    <h1>季排名</h1>
                </div>
                <div class="module-body">
                    <div class="menu-box">
                        <ul class="menu clearfix">
                            <li class="selected"> <a href="javascript:void(0);">总榜</a> </li>
                        </ul>
<!--                        <span class="exercise-result"> 你的登录天数： 6 | 排名： 3990 </span>-->
                    </div>
                    <table>
                        <tbody>
                        <tr>
                            <th width="80">排名</th>
                            <th width="120">用户</th>
                            <th width="280">个性签名</th>
                            <th width="80">志愿时间</th>
                        </tr>

                        <?
                        $quarter_count = 1;
                        foreach ($quarter_datas as $k => $v){?>

                        <tr>
                            <td> <span class="browse-num top-browse top1"> <?=$quarter_count++?> </span> </td>
                            <td class="txt-left">
                                <div class="nker-info">
                                    <a class="nker-name level-color-6" data-card-uid="1724" href="/volunteer/volunteerdetail/id/<?=$v['id']?>" data-card-index="2"><?=$v['username']?></a>
                                </div> </td>
                           <?if(empty($v['content'])){?>
                            <td> ╮(╯▽╰)╭暂无签名 </td>
                            <?}else{?>
                               <td><?=mb_substr($v['content'],0,10,'utf-8')?></td>
                            <?}?>
                            <td class="js-follow-count"><?=$v['quarter_sum_hour']?>小时</td>
                        </tr>

                        <?}?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php include PATH_TPL.'/rank.phtml'?>

</div>

<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>