<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>一起志愿吧</title>
    <meta name="description" content="一起志愿吧" />
    <meta name="keywords" content="一起志愿吧" />
    <link rel="stylesheet" href="/css/honor.css"/>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <!--        head foot样式必须css文件-->
    <!--    列表浮动显示-->
    <script src="/js/sHover.min.js"></script>
    <link rel="stylesheet" href="/css/shover.css">
    <!--        列表浮动显示-->
    <!--    触发提交的js插件--必须-->
    <script src="/static/js/wvke.js" type="text/javascript"></script>
    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<!--        提交的js插件--必须-->



</head>
<body>
<!--head-->
<?php include PATH_TPL.'/head.phtml'?>

<div class="nk-container">
    <div class="nk-main topic-main">

        <!--主体内容-->
        <div class="honor-page clearfix">

            <div class="clearfix" style="padding: 7% 0 0 0;">

<!--                日-->
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>日排名</h1>
                    </div>
                    <div class="menu-box side-tab-box">
                        <ul class="menu clearfix">
                            <li class="selected"><a href="#">总榜</a> </li>
                        </ul>
                    </div>

                    <div class="module-body browse-rank">
                        <!--本周排行榜-->
                        <table>
                            <tbody>
                            <tr>
                                <td width="60">排行</td>
                                <td width="150">用户</td>
                                <td width="150">志愿时间</td>
                            </tr>


                            <?
                            $day_count = 1;
                            foreach ($day_datas as $k => $v){?>

                            <tr>
                                <td> <span class="browse-num top-browse top1"> <?=$day_count++?></span> </td>
                                <td>
                                    <div class="list-name">
                                        <a class="level-color-6" data-card-uid="#" href="/volunteer/volunteerdetail/id/<?=$v['id']?>" data-card-index="2"> <?=$v['username']?> </a>
                                    </div> </td>
                                <td> <?=$v['day_sum_hour']?>小时</td>
                            </tr>
                            <?}?>

                            </tbody>
                        </table>
                        <a href="/rank/detailday" class="all-honor-list js-sort-0">查看全部榜单 &gt;</a>
                    </div>
                </div>
<!--                日-->


                <!--                周-->
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>周排名</h1>
                    </div>
                    <div class="menu-box side-tab-box">
                        <ul class="menu clearfix">
                            <li class="selected"><a href="#">总榜</a> </li>
                        </ul>
                    </div>

                    <div class="module-body browse-rank">
                        <!--本周排行榜-->
                        <table>
                            <tbody>
                            <tr>
                                <td width="60">排行</td>
                                <td width="150">用户</td>
                                <td width="150">志愿时间</td>
                            </tr>

                            <?
                            $week_count = 1;
                            foreach ($week_datas as $k => $v){?>
                            <tr>
                                <td> <span class="browse-num top-browse top1"><?=$week_count++?></span> </td>
                                <td>
                                    <div class="list-name">
                                        <a class="level-color-6" data-card-uid="1724" href="/volunteer/volunteerdetail/id/<?=$v['id']?>" data-card-index="2"><?=$v['username']?></a>
                                    </div> </td>
                                <td><?=$v['week_sum_hour']?>小时</td>
                            </tr>
                            <?}?>
                            </tbody>
                        </table>
                        <a href="/rank/detailweek" class="all-honor-list js-sort-0">查看全部榜单 &gt;</a>
                    </div>
                </div>
                <!--                周-->
                <!--                月-->
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>月排名</h1>
                    </div>
                    <div class="menu-box side-tab-box">
                        <ul class="menu clearfix">
                            <li class="selected"><a href="#">总榜</a> </li>
                        </ul>
                    </div>

                    <div class="module-body browse-rank">
                        <!--本周排行榜-->
                        <table>
                            <tbody>
                            <tr>
                                <td width="60">排行</td>
                                <td width="150">用户</td>
                                <td width="150">志愿时间</td>
                            </tr>
                            <?
                            $month_count = 1;
                            foreach ($month_datas as $k => $v){
                            ?>
                            <tr>
                                <td> <span class="browse-num top-browse top1"><?=$month_count++?></span> </td>
                                <td>
                                    <div class="list-name">
                                        <a class="level-color-6" data-card-uid="1724" href="/volunteer/volunteerdetail/id/<?=$v['id']?>" data-card-index="2"><?=$v['username']?></a>
                                    </div> </td>
                                <td><?=$v['month_sum_hour']?>小时</td>
                            </tr>
                            <?}?>
                            </tbody>
                        </table>
                        <a href="/rank/detailmonth" class="all-honor-list js-sort-0">查看全部榜单 &gt;</a>
                    </div>
                </div>
                <!--                月-->
                <!--                季-->
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>季排名</h1>
                    </div>
                    <div class="menu-box side-tab-box">
                        <ul class="menu clearfix">
                            <li class="selected"><a href="#">总榜</a> </li>
                        </ul>
                    </div>

                    <div class="module-body browse-rank">
                        <!--本周排行榜-->
                        <table>
                            <tbody>
                            <tr>
                                <td width="60">排行</td>
                                <td width="150">用户</td>
                                <td width="150">志愿时间</td>
                            </tr>

                            <?
                            $quarter_count = 1;
                            foreach ($quarter_datas as $k => $v){?>
                            <tr>
                                <td> <span class="browse-num top-browse top1"><?=$quarter_count++?></span> </td>
                                <td>
                                    <div class="list-name">
                                        <a class="level-color-6" data-card-uid="1724" href="/volunteer/volunteerdetail/id/<?=$v['id']?>" data-card-index="2"><?=$v['username']?></a>
                                    </div> </td>
                                <td><?=$v['quarter_sum_hour']?>小时</td>
                            </tr>
                            <?}?>
                            </tbody>
                        </table>
                        <a href="/rank/detailquarter" class="all-honor-list js-sort-0">查看全部榜单 &gt;</a>
                    </div>
                </div>
                <!--                季度-->
                <!--                年-->
                <div class="module-box">
                    <div class="module-head clearfix">
                        <h1>年排名</h1>
                    </div>
                    <div class="menu-box side-tab-box">
                        <ul class="menu clearfix">
                            <li class="selected"><a href="#">总榜</a> </li>
                        </ul>
                    </div>

                    <div class="module-body browse-rank">
                        <!--本周排行榜-->
                        <table>
                            <tbody>
                            <tr>
                                <td width="60">排行</td>
                                <td width="150">用户</td>
                                <td width="150">志愿时间</td>
                            </tr>

                            <?
                            $year_count = 1;
                            foreach ($year_datas as $k => $v){?>
                            <tr>
                                <td> <span class="browse-num top-browse top1"><?=$year_count++?></span> </td>
                                <td>
                                    <div class="list-name">
                                        <a class="level-color-6" data-card-uid="1724" href="/volunteer/volunteerdetail/id/<?=$v['id']?>" data-card-index="2"><?=$v['username']?></a>
                                    </div> </td>
                                <td><?=$v['year_sum_hour']?>小时</td>
                            </tr>
                            <?}?>
                            </tbody>
                        </table>
                        <a href="/rank/detailyear" class="all-honor-list js-sort-0">查看全部榜单 &gt;</a>
                    </div>
                </div>
                <!--                年-->

            </div>

        </div>
    </div>

</div>


<!--foot-->
<?php include PATH_TPL.'/foot.phtml'?>

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>