<a href="/admin/news/add/" class="btn green" href="#"><i class="icon-plus"></i>添加</a>
<div role="grid" class="dataTables_wrapper form-inline">
    <table class="table table-striped table-bordered table-hover dataTable">
        <thead>
        <tr>
            <th>ID</th>
            <th>新闻标题</th>
            <th>新闻内容</th>
            <th>创建时间</th>
            <th>更新时间</th>
            <th width="180px">操作</th>
        </tr>
        </thead>
        <tbody id="table">
        <?
        foreach ($datas as $k1 => $v1) {?>
            <tr>
                <td><?=$v1["id"]?></td>
                <td><?=mb_substr($v1["caption"],0,15,'utf-8')?></td>
                <td><?=mb_substr($v1["content"],0,15,'utf-8')?></td>
                <td><?=$v1["created_at"]?></td>
                <td><?=$v1["updated_at"]?></td>
                <td>
                    <a class="btn btn-xs blue" href="/admin/news/edit/id/<?=$v1['id']?>"><i class="icon-edit"></i> 编辑</a>
                    <a class="btn btn-xs red" onclick="newsdel(<?=$v1['id']?>)"><i class="icon-remove"></i> 删除</a>

                    <?if($v1['status'] == 0){?>
                    <a class="btn btn-xs green" onclick="newsup(<?=$v1['id']?>)"><i class="icon-cloud-upload"></i> 发布</a>
                    <?}else{?>
                        <a class="btn btn-xs yellow" onclick="newsdown(<?=$v1['id']?>)"><i class="icon-cloud-download"></i> 下线</a>
                    <?}?>
                </td>
            </tr>
        <? } ?>
        </tbody>
    </table>
    <?= $page->show() ?>
</div>
<script>
    function newsdel(id){
        if(confirm('即将删除该行,操作不可恢复，是否继续？')) {
            $.post('/admin/news/del', {id: id}, function (d) {
                alert(d.msg);
                if (d.status) location.reload();
            }, 'json');
        }
    }

    function newsup(id) {
        $.post('/admin/news/up', {id: id}, function (d) {
            alert(d.msg);
            if (d.status) location.reload();
        }, 'json');
    }

    function newsdown(id) {
        $.post('/admin/news/down', {id: id}, function (d) {
            alert(d.msg);
            if (d.status) location.reload();
        }, 'json');
    }
</script>