<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <title>志愿基地</title>

    <!--    head foot样式必须css文件-->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/index.css">
<!--            head foot样式必须css文件-->


    <link rel="stylesheet" type="text/css" href="/css/slider-pro.min.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/css/base.css" media="screen"/>

    <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery.sliderPro.min.js"></script>

    <script type="text/javascript">
        $( document ).ready(function( $ ) {
            $( '#base' ).sliderPro({
                width: 960,
                height: 500,
                arrows: true,
                buttons: false,
                waitForLayers: true,
                thumbnailWidth: 200,
                thumbnailHeight: 100,
                thumbnailPointer: true,
                autoplay: false,
                autoScaleLayers: false,
                breakpoints: {
                    500: {
                        thumbnailWidth: 120,
                        thumbnailHeight: 50
                    }
                }
            });
        });
    </script>

</head>

<body>

<!--head start -->
<?php include PATH_TPL.'/head.phtml'?>
<!--head end -->

<div id="base" class="slider-pro">

    <div class="sp-slides">

        <? foreach ($datas as $v){?>

        <div class="sp-slide">
            <a href="/base/basedetail/id/<?=$v['id']?>">
            <img class="sp-image" src="/img/blank.gif"
                 data-src="<?=$v['img']?>"
                 data-retina="<?=$v['img']?>"/>
            </a>
            <p class="sp-layer sp-white sp-padding"
               data-horizontal="50" data-vertical="50"
               data-show-transition="left" data-hide-transition="up" data-show-delay="400" data-hide-delay="200">
                <?=$v['base_name']?>
            </p>

        </div>
        <?}?>

    </div>

    <div class="sp-thumbnails">

        <? foreach ($datas as $v){?>
        <div class="sp-thumbnail">
            <div class="sp-thumbnail-title"><?=$v['base_name']?></div>
            <div class="sp-thumbnail-description"><?=$v['base_name']?></div>
        </div>

        <?}?>

    </div>

</div>
<!--foot start-->
<?php include PATH_TPL.'/foot.phtml'?>
<!--foot end-->

<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/jquery.bootstrap-dropdown-hover.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/index-dropdown.js"></script>

</body>
</html>